### ISSUE TITLE
Unable to extract attachment

### ISSUE THREAD

**Issue by internaut19** [inflex/ripMIME#13]
Hello!

I am trying to extract an attachment from an email received from a Toshiba MF copier and I getting the header the file and a textfile0 with the following content:

Scanned from Toshiba2555CSE
Template test
Test scan
Date:23/03/2020 08:40
Pages:1
Resolution:300x300 DPI
----------------------------------------
Scanned on TOSHIBA2555CSE
No reply.
M1é¯|ÓW5á§4ãMñ¿vïÍwÓ|Ó}
‰íz{SÊ—š¦™bq«b¢éuð¨ž×§µ:ÚžÇÞ¬IÜ¡Ø§¶¬{®¢{^žÐâ²š,ŠØ¨«miÈfz{_ŠW§jg

The email is displayed correctly in a email client like Outlook and I can see the attachment, but with ripmime I cannot extract it. I am using the latest version 1.4.0.10.

If anyone can give me any pointers on how to tackle this, will be greatly appreciated.

Thanks,
Chris

**Comment by inflex** [comment]
Any chance you can provide a copy of the mailpack file ?

**Comment by internaut19** [comment]
Yes, I 've sent it to you via email.

**Comment by internaut19** [comment]
Hello!

Did you get a chance to look at the file that I've sent?

Thanks,
Chris

**Comment by internaut19** [comment]
Hello!

Is there a chance to fix this issue? Time refference, maybe?

Or maybe you can tell me why is this happening so I can try to change something in the machine.

Thanks,
Chris

**Comment by internaut19** [comment]
A simple fix for this was to edit the dumped email, by splitting the following line in two using ; as separator before feeding to ripmime.

Content-Type:Multipart/mixed;boundary="xxxxx"

After that the attachments were extracted successfully.
