### ISSUE TITLE
parameter continuations fail on whitespace

### ISSUE THREAD

**Issue by jimdigriz** [inflex/ripMIME#19]
Well, this is a [new MIME header encoding format for me](https://www.rfc-editor.org/rfc/rfc2231#section-4)...

```
$ ripmime -v --paranoid --overwrite -i Maildir/cur/1663650431.29200_997.hanzawa:2,S -d Workdir/1663650431.29200_997.hanzawa
Decoding filename=textfile0
Decoding filename=textfile1
Decoding filename=Entainlsx
```

The cause of this is:
```
------=_Part_50_1247050508.1663646525365
Content-Type: application/octet-stream;
        name*0="Entain Ladbrokes Coral Yahoo Past 7 days Report
 09-20-2022.x"; name*1=lsx
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
        filename*0="Entain Ladbrokes Coral Yahoo Past 7 days Report
 09-20-2022.x"; filename*1=lsx
...
```

Looks like the parser does not support whitespace when dealing with parameter continuations.

**Comment by inflex** [comment]
Oh joy... even after 20 years there's still stuff to break :)

I don't suppose you have a patch/fix/PR handy for it?

**Comment by jimdigriz** [comment]
I do not, but the options here are:
1. I add this to my TODO list as I have a client I can bill to get this resolved; I'm busy for the next eight or so weeks on other projects
2. I sub-contract you

Both work for me.

**Comment by inflex** [comment]
Release #1.4.1.0 should resolve this issue as well has including some recent PRs and some minor fixes.
